server:
  port: 8080
  servlet:
    context-path: /inventory-service/api/v1.0
  display-name: Inventory Service
  session:
    timeout: 1000


# datasource
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_db?serverTimezone=UTC
    username: admin
    password: admin@123
    validationQuery: "SELECT 1"
#spring.jpa.hibernate.naming.physical.strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"


# swagger-ui config
springdoc:
  api-docs:
    path: /admin/v3/api-docs
  swagger-ui:
    path: /admin/swagger-ui.html
  model-converters:
      pageable-converter:
        enabled: true